management:
  info:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
