spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #多个文件,分隔
          searchLocations: classpath:/service-config,classpath:/service-config/user,classpath:/service-config/order
server:
  port: 8080
