server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: monitor
spring:
  applicaiton:
    name: config-server
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
